spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.mingbxukwyoovoamwgnu
    password: aj4ua9dCihYDazSJ
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      pool-name: HikariCP
      connection-timeout: 20000
      idle-timeout: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update # You can change this to 'validate', 'create', 'none' as needed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect







